### ISSUE TITLE
Unfromatted data to QF rule callback

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#151]
The call to `Utils_RecordBrowserCommon::check_record_against_crits` [here](https://github.com/Telaxus/EPESI/blob/testing/modules/Utils/RecordBrowser/RecordBrowser_0.php#L1409) will not produce correct results as the `$data` variable contains unformatted data. For timestamp field for instance it is:

```
array (size=2)
      '__date' => 
        array (size=2)
          'H' => string '0' (length=1)
          'i' => string '0' (length=1)
      '__datepicker' => string '29 December 2016' (length=16)
```

**Comment by bukowskiadam** [comment]
To make it clean we should move record validation upon create to `new_record/edit_record` method. Throw some exception when it doesn't match rules (required fields and other). But it'll break some modules, because now creating record programatically allows to omit those rules. Also now each rule is just a quickform(view) rule, but it should be data validation rule. So it's pretty complicated.

**Comment by jtylek** [comment]
The project is no longer maintained and it was moved to: https://github.com/jtylek/Epesi
