### ISSUE TITLE
[ENHANCEMENT] Recurring tasks

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#46]
I would like to share an idea about option for recurring tasks for the CRM/Tasks.
The recurring schedule can be selected via a jQuery cron maker plugin like [cronGen](https://github.com/hsal/cronGen) and the cron expression saved in a designated field. Every due date will then be added to the Agenda based on evaluation of the cron expression.

regards,
Georgi
##

**Comment by jtylek** [comment]
We wil be rewriting the Calendar to make it compatible with iCal. Probably something like this:
https://github.com/markuspoerschke/iCal

My plan is to create a table with structure compatible with iCal specification:
http://stackoverflow.com/questions/1054201/ical-field-list-for-database-schema-based-on-ical-standard

I would like the recurring tasks to be handled the same way to allow external calendar applications like Google Calendar for example, or if someone wishes to subscribe to epesi calendar from Outlook - this feature was requested many times and there is even a module to generate ical files:
https://github.com/jjjj12212/EPESI-Ical
https://forum.epesibim.com/d/2968-ical-export/9

## Proposed changes

### The Calendar module will simply be a COLLECTION events:

- Meeitngs
- Tasks (To-Do)
- Phone Calls
- Tickets
- Timesheets
- Vacations (Days Off, Sick etc.)
- and others...

**Calendar** will have to register events simply as an entry in a table (hook) and it will be recognized as a **EVENT_TYPE**
The Calendar table itself will be compatible with iCal standard and we will use an existing PHP library for that. Because of the standard we can then easily parse this table and plugin data into Bootstrap ready calendar template and even get it as JSON because this is already well solved. We need it anyway.

When Calendar data is modified - for example by external application like Google Calendar - then post-process event will have to be fired to update the child EVENT_TYPE details like date and time for example. In other words the master Calendar table would have to be kept in sync with all child events tables:
tbl_events_meetings
tbl_events_tasks
tbl_events_phonecalls etc.
In the future one could easily create a module with another handler to the calendar hooks list, which will automatically be selectable in the list of actions - and we can provide a GUI for the admin to select which actions are active for example - even based on group permissions. This would be necessary anyway as we can not list a full set of events in every case - for example a customer portal can not display add Vacation but only for example Calendar, Tasks and Tickets.

**Comment by jtylek** [comment]
http://stackoverflow.com/questions/10320644/ical-backend-recurring-dates
http://stackoverflow.com/questions/4239871/should-i-store-dates-or-recurrence-rules-in-my-database-when-building-a-calendar/10163834#10163834

**Comment by jtylek** [comment]
"OCCURRENCES WISE: for occurences you should store instances within a predefined window around present (say +/- 6 months or 12months and computed on a regular basis) and keep records of this to allow re-calculation if your users want to see further in the future (for performances issues). you should also consider computing the index (RECURRENCE-ID) to help easier finding of the next occurrence."

@georgehristov - and we could use simply epesi cron job to re-calculate changes or fire alerts and reminders.

**Comment by jtylek** [comment]
The project is no longer maintained and it was moved to: https://github.com/jtylek/Epesi
