### ISSUE TITLE
Utils_RecordBrowser recursive access on limited field list

### ISSUE THREAD

**Issue by georgehristov** [Telaxus/EPESI#81]
Calling `Utils_RecordBrowser::get_records` method returns empty array instead of proper results when all below conditions are fulfilled:
- user has limited access to records based on recursive rule on a field (I have not tested with direct acces rule on a field)
- `$cols` parameter is set with a list of fields which does not include the field that has an access rule set

When the field that has access rule is included in `$col` then the method returns correct results.

**Comment by georgehristov** [comment]
The SQL statement within `Utils_RecordBrowser::get_records` returns correct results and problem seems to be with the php check of each record with `Utils_RecordBrowser::get_access`

**Comment by bukowskiadam** [comment]
I'll review this as I'm currently working on access rules code. Thanks

**Comment by georgehristov** [comment]
Just as update - actually the method fails on all users (except admin) if the recordset has a rule on a field and this field is not in the `$col` parameter.

PS: any plan to include a possible access callback functionality (legacy access_callback field is still being installed on the recordbrowser_table_properties).

**Comment by bukowskiadam** [comment]
In fact it's the reason why I'm working on access rules. But I'd like to create separate table for access callbacks to allow define more than one. Possible results of access callback will be:
- don't allow to record - don't check crits
- allow to record - don't check crits
- return crits and check for record
- do not affect access

**Comment by georgehristov** [comment]
Sounds great!

**Comment by bukowskiadam** [comment]
Access callback rules are ready, but I haven't tested them extensively, but used in Attachments.

About this issue with access and cols. There are several possible solutions:

1. do not use cols param at all and always retrieve all data from record
2. always retrieve all data, check access with all data, then return just cols wanted
3. Try to estimate from access, which cols are required to properly check access and fetch those cols also.

Easiness of coding: 1 > 2 > 3
I'm not sure if **3.** is possible - just the idea.
In the ideal RB i wouldn't allow to use PHP access check, because it makes some issues with performace, however I don't see better solution right now.

**Comment by georgehristov** [comment]
My idea was directly at **3.** and I briefly looked into it (ways to retrieve cols from access crits and merge with `$cleancols`) but it is really not so straight forward.
No **1.** is a "quick fix" but I am not sure how it will affect performance. Guess **2.** will be even a bit worse on performance.
Anyway a fix must be applied as some core modules are affected from this bug (like RecordPickerFS)

**Comment by georgehristov** [comment]
How about such concept in `get_records` if `$cols` parameter is not empty:
- call `get_access` method with `$return_crits` option to get the access crits
- retrieve all fields from the access crits and merge them with `$cleancols`

**Comment by bukowskiadam** [comment]
That's exactly the implementation of 3rd case, but it won't allow to use other cols in access callback. So i don't see any other reasonable solution.
